import numpy as np
print()
print("Enter no. of elements in array 1:")
n = int(input())
print()
print("Enter inputs for array 1:")
arr1 = input()
x = list(map(int,arr1.split(' ')))
print()
print("First array:")
print()
print(x)
print()
print("Enter no. of elements in array 2:")
m = int(input())
print()
print("Enter inputs for array 2:")
arr2 = input()
y = list(map(int,arr2.split(' ')))
print()
print("Second array:")
print()
print(y)
print()
print()
array_equal = np.allclose(x, y)
if (array_equal):
    print("The arrays are equal, So True")
else:
    print("The arrays are not equal, So False")
    
